### ISSUE TITLE
Use another word boundaries

### ISSUE THREAD

**Issue by alexandrtovmach** [Trott/remark-lint-prohibited-strings#10]
@Trott  Thanks for amazing tool.
I'm working now on preset for Gatsby docs, and faced with weird thing.

Markdown to parse:
```markdown
Some text [gatsby-plugin-create-client-paths](/packages/gatsby-plugin-create-client-paths)
```
Plugin rule:
```js
[{ no: "gatsby", yes: "Gatsby" }]
```
Error message:
> warning  Use "Gatsby" instead of "gatsby"  prohibited-strings  remark-lint

I think this can be fixed by using another way to set boundaries with `\s`:
```js
const re = new RegExp(`(\\.|@[a-z0-9/-]*)?\\s(${val.no})\\s(\\.\\w)?`, 'g');
```

**Comment by alexandrtovmach** [comment]
After a few tests I think the problem only in symbols after word, so maybe better:
`const re = new RegExp(`(\\.|@[a-z0-9/-]*)?\\b(${val.no})\\s(\\.\\w)?`, 'g');`

**Comment by alexandrtovmach** [comment]
@Trott Please take a look on this example of regex https://regex101.com/r/DcoRGM/2

**Comment by alexandrtovmach** [comment]
I think it can simplify current regex

**Comment by Trott** [comment]
You can use a regular expression in the config file to allow a hyphen following the string:

```
[{ no: "gatsby(?!\\-)", yes: "Gatsby" }]
```

Will that meet your needs? I dislike the idea of introducing this change by default because I want it to flag hyphenated examples. For example, if there was text about "the gatsby-specific way to handle this situation", I want the linter to catch that. If someone wants to opt out of that, I'm OK with making them do a little extra work like the above.

Another option is to disable the rule for that one line with comments:

```
<!--lint disable prohibited-strings-->
Some text [gatsby-plugin-create-client-paths](/packages/gatsby-plugin-create-client-paths)
<!--lint enable prohibited-strings-->
```

**Comment by alexandrtovmach** [comment]
@Trott Okay, thank you that's work for me, but my point is `cebab-case` should be validated by default. For example, names of npm packages or git repository names

**Comment by Trott** [comment]
> @Trott Okay, thank you that's work for me, but my point is `cebab-case` should be validated by default. For example, names of npm packages or git repository names

If the text is in a code block or inside backticks, it will be ignored by this plugin, so kebab-case will be fine in that situation. But if it's in link text, like in your example above, it will be checked.

**Comment by Trott** [comment]
> > @Trott Okay, thank you that's work for me, but my point is `cebab-case` should be validated by default. For example, names of npm packages or git repository names
> 
> If the text is in a code block or inside backticks, it will be ignored by this plugin, so kebab-case will be fine in that situation. But if it's in link text, like in your example above, it will be checked.

Incidentally, this implies a third possible solution:

```
Some text [`gatsby-plugin-create-client-paths`](/packages/gatsby-plugin-create-client-paths)
```

**Comment by alexandrtovmach** [comment]
Yes, I think this is the best solution https://github.com/Trott/remark-lint-prohibited-strings/issues/10#issuecomment-545072787

Thank you

**Comment by alexandrtovmach** [comment]
@Trott And one more case:
`<https://www.gatsbyjs.org/starters/gatsby>`

This should be handled, but itsn't

**Comment by Trott** [comment]
> @Trott And one more case:
> `<https://www.gatsbyjs.org/starters/gatsby>`
> 
> This should be handled, but itsn't

@alexandrtovmach I think it should flag that and this is a case where the best thing to do is to disable the rule with a comment. When the AST arrives to the lint plugin, that markdown is expanded into a link and the link text provided to the linter is `https://www.gatsbyjs.org/starters/gatsby`. That trailing `gatsby` is what the lint rule is catching and I think that's right. Otherwise, it wouldn't catch markdown like this:

```markdown
Check out [gatsby/others](https://www.example.com) for what to do for Gatsby and other static-site generators!
```

Furthermore, there's no guarantee that this plugin is being used to deal with typography issues only. It might be used for common misspellings (in which case we definitely want it flagging `gastby` or whatever) or if a product is renamed. (Didn't Gatsby used to be...something else? Let's say it used to be named Kyle. We'd want the plugin to notice the word `Kyle` in a URL path. The user might need to disable the plugin with a comment for that one line if it's, say, not being redirected or doesn't have a valid URL in the new project yet. But that's a choice a human should make after reviewing. And in that case, even adding additional stuff to check that the link-text isn't a valid URL would still be a problem because we want `Kyle` flagged. All things being equal, I think it's best to keep the rule simple and trying to fix this will mean trying to add some magic. So I think this exception is best handled with a disabling comment.)
